OUTPUT_ARCH(riscv)
ENTRY(_start)

MEMORY {
    RAM    : org = 0x0000000080200000, len = 4M
    KBSS   : org = 0xffffffff40000000, len = 2M
    KIMAGE : org = 0xffffffff80200000, len = 2M
}

REGION_ALIAS("REGION_TEXT", KIMAGE);
REGION_ALIAS("REGION_RODATA", KIMAGE);
REGION_ALIAS("REGION_DATA", KIMAGE);
REGION_ALIAS("REGION_BSS", KBSS);
REGION_ALIAS("REGION_EHFRAME", KIMAGE);

_stext = ORIGIN(REGION_TEXT) + LOADADDR(.text) - ORIGIN(RAM);
