[build]
target = "riscv64gc-unknown-none-elf"
target-dir = 'build'
rustflags = ["-C", "force-unwind-tables"]

[unstable]
build-std-features = ['compiler-builtins-mem']
build-std = ['core', 'compiler_builtins', 'alloc']
